workflows:
  build-workflow:
    name: Build Android APK via Drive ZIP
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Download project from Google Drive
        script: |
          # Google Drive se ZIP download karo
          DRIVE_LINK="https://drive.google.com/uc?export=download&id=1NavTMPjhc0OGQypx2nzC-t7AeZQEBl29"
          curl -L "$DRIVE_LINK" -o project.zip
          unzip project.zip -d project
          cd project
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - project/build/app/outputs/flutter-apk/*.apk
