workflows:
  build-from-limewire-zip:
    name: Build from LimeWire ZIP
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Download ZIP from LimeWire
        script: |
          echo "Downloading ZIP..."
          curl -L -o project.zip "https://limewire.com/d/sNTR9#PwDZ0Dgork"
      - name: Unzip project
        script: |
          unzip -q project.zip -d project_unzip
          TOPDIR=$(find project_unzip -mindepth 1 -maxdepth 1 -type d | head -n 1)
          echo "Top-level dir: $TOPDIR"
          rsync -a "$TOPDIR/" .
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients: []
