workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter dependencies
        script: |
          cd final_project_root_ready
          flutter pub get

      - name: Build release APK
        script: |
          cd final_project_root_ready
          flutter build apk --release

    artifacts:
      - final_project_root_ready/build/app/outputs/flutter-apk/app-release.apk
