workflows:
  flutter-workflow:
    name: Flutter Build (Android + iOS)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      # Android build
      - name: Build Android APK
        script: |
          flutter build apk --release

      # iOS build
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
