workflows:
  android-app:
    name: Build Android App
    environment:
      sdk: flutter
      flutter: stable
    scripts:
      - name: Download project from Google Drive
        script: |
          echo "Downloading project zip..."
          wget -O project.zip "https://drive.google.com/uc?export=download&id=1NavTMPjhc0OGQypx2nzC-t7AeZQEBl29"
          unzip project.zip -d project
          cd project
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
