name: bt_audio_recever
description: Bt audio recever - single app (Primary/Secondary) ready for Codemagic build
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.2
  flutter_webrtc: ^0.9.20
  permission_handler: ^10.4.0
  flutter_sound: ^9.2.13
  phone_state: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
